### ISSUE TITLE
Installing Pytorch taking a long time

### ISSUE THREAD

**Issue by resol341** [kf-cuanschutz/CU-Anschutz-HPC-documentation#3]
Hi, I don't know if this is the right place to ask question or submitting ticket is the preferred method. 

I am following the posted instrumentation for installing Pytorch. But it has been stuck on "Solving environment" for quite a while now. Is there a way around this? 

I have heard that conda is quite inefficient and a lot of packages recommend using mamba instead. Is there a recommended way to use mamba on the Alpine? 

Thank you.

**Comment by kf-cuanschutz** [comment]
Hi,

Thank you for pointing this out.
You may try the following:

1) Copy your .condarc to .mambarc. For example: 
```bash
cp ~/.condarc ~/.mambarc
```

Note: Your ~/.mambarc file should contain something similar to the following: 

```bash
pkgs_dirs: 
- /projects/$USER/.conda_pkgs 
envs_dirs: 
- /projects/$USER/software/anaconda/envs 
```

2) Build packages with:
```bash     
acompile --ntasks=4 --time=01:00:00 
```

3) Load mamba forge: 
```bash    
module load mambaforge/23.1.0-1 
```

4) You can look at both your mamba and conda environments with: 
```bash    
mamba info -e
``` 

5) Create your environment with python 3.10 and activate it.
```bash
mamba create -n pytorch_env python=3.10 
mamba activate pytorch_env
```


6) Install pytorch, pytorch-cuda. You could also install torchvision and torchaudio if needed for your workflow.

```bash
mamba install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia 
```

7) Install cuda-toolkit 11.8.0:
```bash
mamba install -c "nvidia/label/cuda-11.8.0" cuda-toolkit 
```

8) To test that your installation is working you will need to exit "acompile" first and load on the NVIDIA gpu debug partition on Alpine:
```bash
mamba deactivate
exit
sinteractive --partition=atesting_a100 --qos=testing --time=00:05:00 --gres=gpu:1 --ntasks=2
module load  mambaforge/23.1.0-1
mamba activate pytorch_env
python
```

9)  Finally, run the following:
```python
>>>import torch
>>>print(torch.cuda.is_available())
True
```

10) Make sure to exit the GPU debug node partition after testing the installation.
```bash
$ exit
```

**Comment by resol341** [comment]
Thank you!! Worked like a charm.

**Comment by kf-cuanschutz** [comment]
Super! Fantastic to hear!
